version: "3"
services:
  client-app:
    image: client-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern
  server-app:
    image: server-app
    ports:
      - "5000:5000"
    networks:
      - mern
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongodb:/data/db
networks:
  mern:
    driver: bridge
volumes:
  mongodb:
    driver: local
